version: '3.8'

services:
  backend:
    build:
      context: ./ATS/backend
      dockerfile: Dockerfile
    container_name: ats-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./ATS/frontend
      dockerfile: Dockerfile
    container_name: ats-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
